name: backend-deploy
description: Deploy backend Cloud Run service
inputs:
  region:
    required: true
    description: GCP region
  service_name:
    required: true
  project_id:
    required: true
  artifact_repo:
    required: true
  service_account_email:
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploy Backend Cloud Run
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.artifact_repo }}/${{ inputs.service_name }}:latest"
        gcloud run deploy "${{ inputs.service_name }}" \
          --image "$IMAGE_URI" \
          --platform managed \
          --region "${{ inputs.region }}" \
          --service-account "${{ inputs.service_account_email }}" \
          --allow-unauthenticated \
          --cpu 1 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 1 \
          --set-env-vars RAILS_ENV=production,RAILS_LOG_TO_STDOUT=true,RAILS_SERVE_STATIC_FILES=true \
          --set-secrets "DATABASE_URL=jira-task-database-url:latest,RAILS_MASTER_KEY=jira-task-rails-master-key:latest,SECRET_KEY_BASE=jira-task-secret-key-base:latest"
