name: backend-test
description: Run backend test suite
inputs:
  ruby_version:
    required: false
    default: "3.3"
    description: Ruby version to install
runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    - name: Install libpq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev
    - name: Test Backend
      shell: bash
      env:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: postgres
        PGDATABASE: backend_test
      run: |
        cd backend
        bundle install --jobs=4 --retry=3
        bundle exec rails db:prepare
        bundle exec rails test
