name: backend-test
description: Run backend test suite
inputs:
  ruby_version:
    required: false
    default: "3.3"
    description: Ruby version to install
runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    - name: Test Backend
      shell: bash
      run: |
        cd backend
        bundle install --jobs=4 --retry=3
        bundle exec rails test
