name: frontend-build
description: Build and push frontend image to Artifact Registry
inputs:
  region:
    required: true
  project_id:
    required: true
  artifact_repo:
    required: true
  service_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure Artifact Registry Docker Auth
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet
    - name: Build and Push Frontend Image
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.artifact_repo }}/${{ inputs.service_name }}:latest"
        docker build -t "$IMAGE_URI" ./frontend
        docker push "$IMAGE_URI"
