name: terraform-run
description: Init and run terraform action
inputs:
  working_directory:
    required: true
  action:
    required: true
    description: Terraform subcommand (plan/apply/destroy)
  var_file:
    required: false
    default: terraform.tfvars.example
  auto_approve:
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      shell: bash
      run: |
        cd "${{ inputs.working_directory }}"
        terraform init
    - name: Terraform Run
      shell: bash
      run: |
        cd "${{ inputs.working_directory }}"
        CMD=(terraform "${{ inputs.action }}" -var-file="${{ inputs.var_file }}")
        if [ "${{ inputs.auto_approve }}" = "true" ]; then
          CMD+=("-auto-approve")
        fi
        "${CMD[@]}"
