name: Checkout, Auth, Build and Push Images
steps:
  - checkout: actions/checkout@v4
  - auth: google-github-actions/auth@v2
    with:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  - setup_gcloud: google-github-actions/setup-gcloud@v2
    with:
      install_components: gcloud,gke-gcloud-auth-plugin
  - verify_docker_token:
      run: |
        if [ -z "${DOCKER_TOKEN:-}" ]; then
          echo "DOCKER_TOKEN secret is required for Docker Hub pushes" >&2
          exit 1
        fi
  - docker_login:
      run: echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USERNAME --password-stdin
  - build_push_backend:
      run: |
        BACKEND_IMAGE="$DOCKER_USERNAME/$BACKEND_SERVICE:latest"
        docker build -t $BACKEND_IMAGE ./backend
        docker push $BACKEND_IMAGE
  - build_push_frontend:
      run: |
        FRONTEND_IMAGE="$DOCKER_USERNAME/$FRONTEND_SERVICE:latest"
        docker build -t $FRONTEND_IMAGE ./frontend
        docker push $FRONTEND_IMAGE
