name: Checkout, Auth, Build and Push Images
steps:
  - checkout: actions/checkout@v4
  - auth: google-github-actions/auth@v2
    with:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  - setup_gcloud: google-github-actions/setup-gcloud@v2
    with:
      install_components: gcloud,gke-gcloud-auth-plugin
  - configure_docker:
      run: gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
  - build_push_backend:
      run: |
        BACKEND_IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/jira-task/${BACKEND_SERVICE}:latest"
        docker build -t $BACKEND_IMAGE ./backend
        docker push $BACKEND_IMAGE
  - build_push_frontend:
      run: |
        FRONTEND_IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/jira-task/${FRONTEND_SERVICE}:latest"
        docker build -t $FRONTEND_IMAGE ./frontend
        docker push $FRONTEND_IMAGE
