name: backend-build
description: Build and push backend image to Artifact Registry
inputs:
  region:
    required: true
    description: GCP region (e.g., us-central1)
  project_id:
    required: true
    description: GCP project ID
  artifact_repo:
    required: true
    description: Artifact Registry repo name
  service_name:
    required: true
    description: Service/image name
runs:
  using: "composite"
  steps:
    - name: Configure Artifact Registry Docker Auth
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev --quiet
    - name: Build and Push Backend Image
      shell: bash
      run: |
        IMAGE_URI="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.artifact_repo }}/${{ inputs.service_name }}:latest"
        docker build -t "$IMAGE_URI" ./backend
        docker push "$IMAGE_URI"
