name: auth-gcp
description: Authenticate to GCP via WIF and set up gcloud
inputs:
  workload_identity_provider:
    required: true
    description: Full WIF provider resource name
  service_account_email:
    required: true
    description: Service account to impersonate
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account_email }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: gcloud,gke-gcloud-auth-plugin
