name: frontend-test
description: Run frontend tests
runs:
  using: "composite"
  steps:
    - name: Test Frontend
      shell: bash
      run: |
        cd frontend
        npm ci
        npm run test --if-present
