name: Deploy Backend
steps:
  - run: |
      BACKEND_IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO}/${BACKEND_SERVICE}:latest"
      gcloud run deploy $BACKEND_SERVICE \
        --image $BACKEND_IMAGE \
        --platform managed \
        --region $REGION \
        --allow-unauthenticated \
        --cpu 1 \
        --memory 512Mi \
        --min-instances 0 \
        --max-instances 1 \
        --set-env-vars RAILS_ENV=production
