name: Deploy Frontend
steps:
  - run: |
      FRONTEND_IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO}/${FRONTEND_SERVICE}:latest"
      gcloud run deploy $FRONTEND_SERVICE \
        --image $FRONTEND_IMAGE \
        --platform managed \
        --region $REGION \
        --allow-unauthenticated \
        --cpu 1 \
        --memory 512Mi \
        --min-instances 0 \
        --max-instances 1 \
        --port 80
